# Generated by Django 4.0.3 on 2022-05-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_responsible',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
