# Generated by Django 4.0.3 on 2022-05-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dds',
            name='read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dds',
            name='readDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
