# Generated by Django 4.0.3 on 2022-05-19 23:51

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dds',
            name='backImg',
            field=models.ImageField(blank=True, default='', help_text='Insert Back Image', null=True, upload_to=home.models.changeImgName, verbose_name='Front Image'),
        ),
    ]
