# Generated by Django 4.0.3 on 2022-05-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrolanswer',
            name='fk_patroweek',
        ),
        migrations.DeleteModel(
            name='PatrolWeek',
        ),
    ]
