# Generated by Django 4.0.3 on 2022-05-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dds_read_dds_readdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dds',
            name='read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
