# Generated by Django 4.0.3 on 2022-05-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_simpleuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
