# Generated by Django 4.0.3 on 2022-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_patrolanswer_fk_patroweek_delete_patrolweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibleanswer',
            name='answerBool',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
