# Generated by Django 4.0.3 on 2022-05-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_patrolweek_fk_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrolweek',
            name='fk_answers',
            field=models.ManyToManyField(blank=True, null=True, to='home.patrolanswer'),
        ),
    ]
