# Generated by Django 4.0.3 on 2022-05-20 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_possibleanswer_answerbool'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolanswer',
            name='fk_patrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
