# Generated by Django 4.0.3 on 2022-05-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_patrolweek_fk_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrolweek',
            name='fk_answers',
        ),
        migrations.RemoveField(
            model_name='patrolweek',
            name='fk_quests',
        ),
        migrations.CreateModel(
            name='PatrolDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cDate', models.DateField(help_text='Insert The Initial Patrol Date', verbose_name='Initial Date')),
                ('fk_answers', models.ManyToManyField(blank=True, null=True, to='home.patrolanswer')),
                ('fk_quests', models.ManyToManyField(to='home.patrolquest')),
            ],
        ),
        migrations.AddField(
            model_name='patrolweek',
            name='fk_days',
            field=models.ManyToManyField(blank=True, null=True, to='home.patrolday'),
        ),
    ]
