# Generated by Django 4.0.3 on 2022-05-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_simpleuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamevent',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.event'),
        ),
        migrations.AddField(
            model_name='teamevent',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.team'),
        ),
    ]
