# Generated by Django 4.0.3 on 2022-05-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_patrolweek_fk_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrolday',
            name='fk_quests',
        ),
        migrations.AddField(
            model_name='patrolweek',
            name='fk_quests',
            field=models.ManyToManyField(to='home.patrolquest'),
        ),
    ]
